#!/bin/bash

# install
# Installs the CLI to /usr/bin/dabbu-cli (executables at $HOME/.local/opt/dabbu/)
# 
# Usage: ./install
# Options:
#     -h       Show usage
#     -d       Simply show what is going to happen
#
# NOTE: This install script is ONLY FOR LINUX/MACOS. Do NOT run this on Windows (it most probably won't work, not tested)

# What happens during installation:
# - Create the /usr/bin directory
# - Create the $HOME/.local/opt/dabbu/files-api-server directory
# - Download the CLI and Files API Server executables to the respective directories
# - Download the wrapper shell script and save it to /usr/bin/
# - Copy the wrapper to /usr/bin/dabbu-cli
# Done!

# ANSI colour codes so we can highlight text in the terminal
colour_black="\033[0;30m"
colour_darkgray="\033[1;30m"
colour_red="\033[0;31m"
colour_lightred="\033[1;31m"
colour_green="\033[0;32m"
colour_lightgreen="\033[1;32m"
colour_orange="\033[0;33m"
colour_yellow="\033[1;33m"
colour_blue="\033[0;34m"
colour_lightblue="\033[1;34m"
colour_purple="\033[0;35m"
colour_lightpurple="\033[1;35m"
colour_cyan="\033[0;36m"
colour_lightcyan="\033[1;36m"
colour_lightgray="0;\033[37 m"
colour_white="\033[1;37m"

# Escape codes for making text bold, italic, etc.
bold="\e[1m"
italic="\e[3m"
underline="\e[4"
strikethrough="\e[9"
normal="\e[0m"

# Show a help message
function help {
	echo -e "${colour_cyan}${bold}install${normal}"
	echo -e "${colour_blue}Installs the Dabbu CLI${normal}"
	echo -e ""
	echo -e "Usage: ${colour_cyan}./install${normal}"
	echo -e ""
	echo -e "${color_cyan}Options:${normal}"
	echo -e "${color_blue}    -h       Show usage${normal}"
	echo -e "${color_blue}    -d       Simply show what is going to happen${normal}"
	echo -e ""
	echo -e "${colour_red}NOTE: This install script is ONLY FOR LINUX/MACOS. Do NOT run this${normal}"
	echo -e "${colour_red}on Windows (it most probably won't work, not tested)${normal}"
	
	exit
}

# Explain what the script does
function dry_run {
	echo -e "${colour_blue}${colour_cyan}What will happen during installation:${normal}"
	echo -e "${colour_blue}- Download the latest CLI${normal}"
	echo -e ""
	echo -e "${colour_blue}To view the source code, go \e]8;;https://github.com/dabbu-knowledge-platform/cli/blob/develop/installers/linux-and-macos/install\ahere\e]8;;\a (https://github.com/dabbu-knowledge-platform/cli/blob/develop/installers/linux-and-macos/install).${normal}"
	
	exit
}

# The actual function that installs the CLI
function install {
	echo -e "${colour_blue}Installing dabbu to ${colour_cyan}/usr/bin/dabbu-cli${colour_blue}${normal}"
	echo -e "${colour_red}You might need to run this script with sudo${normal}"

	echo -e "${colour_blue}Checking environment...${normal}"

	# Check that we are running on either linux or mac
	machine="$(uname -s)"
	case "$machine" in
			Linux*)  machine="linux";;
			Darwin*) machine="macos";;
			*)       machine="unknown";;
	esac

	# If not, error out
	if [ $machine == "unknown" ]; then
		echo -e "${colour_red}This install script is meant only for Linux/MacOS${normal}"
		exit 1
	fi
	echo -e "${colour_blue}Downloading CLI executable to ${colour_cyan}/usr/bin/dabbu-cli${colour_blue}... (This may require your [sudo] password)${normal}"

	# Download the latest release version of the CLI from Github
	sudo curl -L "https://github.com/dabbu-knowledge-platform/cli/releases/latest/download/cli-$machine" --output "/usr/bin/dabbu-cli" --progress-bar
	# Make it an executable
	sudo chmod 755 "/usr/bin/dabbu-cli"

	echo -e "${colour_green}${bold}Successfully installed Dabbu CLI! Type dabbu-cli to run it.${normal}"

	exit
}

# The main function
function main {
	# Fail fast, don't skip errors
	set -e -o pipefail

	# Print the CLI logo (though it is in blue)
	echo -e "${colour_cyan}${bold}  ____        _     _            ${normal}"
	echo -e "${colour_cyan}${bold} |  _ \  __ _| |__ | |__  _   _  ${normal}"
	echo -e "${colour_cyan}${bold} | | | |/ _\` | '_ \| '_ \| | | | ${normal}"
	echo -e "${colour_cyan}${bold} | |_| | (_| | |_) | |_) | |_| | ${normal}"
	echo -e "${colour_cyan}${bold} |____/ \__,_|_.__/|_.__/ \__,_| ${normal}"
	echo -e "${colour_cyan}${bold}                                 ${normal}"

	# Parse options, if specified
	while getopts "hd" opt; do
		case $opt in
			h) help;; # If the option is -h, show help and exit
			d) dry_run;; # If the option is -d, just show what will happen and exit
			esac
	done

	# Else by default run the install process
	install
}

# Call the main function with the options provided
main "$*"
