#!/bin/bash

# ci
# Runs the Typescript Compiler, then the linter, then all tests, and finally builds the packages

# Build the CLI
yarn build
# Run the linter
yarn lint
# Run all tests
yarn test
# Build packages
yarn package
