#!/bin/bash

# package
# Builds packages for linux (deb, rpm, pacman, apk, zip), macos (pkg, zip) and win (zip)
# 
# Usage: scripts/package [<new-version> | major | minor | patch | premajor | preminor | prepatch | prerelease]
# 
# Remember to run this script from the root of the project!

# ANSI colour codes so we can highlight text in the terminal
colour_red="\033[0;31m"
colour_green="\033[0;32m"
colour_blue="\033[0;34m"
colour_cyan="\033[0;36m"

# Escape codes for making text bold and returning it back to normal
bold="\e[1m"
normal="\e[0m"

# Display a help message
function help {
	echo -e "${colour_cyan}${bold}package${normal}"
	echo -e "${colour_blue}Builds packages for linux (deb, rpm, pacman, apk, zip), macos (zip) and win (zip)${normal}"
	echo -e ""
	echo -e "Usage: ${colour_cyan}scripts/package${normal}"
	echo -e ""
	echo -e "${colour_cyan}Remember to run this script from the root of the project!${normal}"
}

# Compile a deb for linux
function compile_linux_deb {
	echo -e "${colour_blue}Compiling linux_deb${normal}"
	
	fpm -s dir -t deb -p dist/packages/dabbu-cli-`cat version`-linux-deb-amd64.deb --name dabbu-cli --license gpl3 --version `cat version` --description "A CLI that enables you to access any of your personal information (Gmail, Google Drive, OneDrive, your hard drive, ...) as simple files and folders" --url "https://dabbu-knowledge-platform.github.io" --maintainer "Vedant K (gamemaker1) <dabbuknowledgeplatform@gmail.com>" ./dist/binaries/cli-linux=/usr/bin/dabbu-cli ./assets/packaging/dabbu-cli.1=/usr/share/man/man1/dabbu-cli.1 ./assets/logo.png=/usr/share/icons/dabbu-cli.png ./assets/packaging/dabbu-cli.desktop=/usr/share/applications/dabbu-cli.desktop
}

# Compile a rpm for linux
function compile_linux_rpm {
	echo -e "${colour_blue}Compiling linux_rpm${normal}"
	
	fpm -s dir -t rpm -p dist/packages/dabbu-cli-`cat version`-linux-rpm-amd64.rpm --name dabbu-cli --license gpl3 --version `cat version` --description "A CLI that enables you to access any of your personal information (Gmail, Google Drive, OneDrive, your hard drive, ...) as simple files and folders" --url "https://dabbu-knowledge-platform.github.io" --maintainer "Vedant K (gamemaker1) <dabbuknowledgeplatform@gmail.com>" ./dist/binaries/cli-linux=/usr/bin/dabbu-cli ./assets/packaging/dabbu-cli.1=/usr/share/man/man1/dabbu-cli.1 ./assets/logo.png=/usr/share/icons/dabbu-cli.png ./assets/packaging/dabbu-cli.desktop=/usr/share/applications/dabbu-cli.desktop
}

# Compile a pacman package for linux
function compile_linux_pacman {
	echo -e "${colour_blue}Compiling linux_pacman${normal}"
	
	fpm -s dir -t pacman -p dist/packages/dabbu-cli-`cat version`-linux-arch-amd64.tar.gz --name dabbu-cli --license gpl3 --version `cat version` --description "A CLI that enables you to access any of your personal information (Gmail, Google Drive, OneDrive, your hard drive, ...) as simple files and folders" --url "https://dabbu-knowledge-platform.github.io" --maintainer "Vedant K (gamemaker1) <dabbuknowledgeplatform@gmail.com>" ./dist/binaries/cli-linux=/usr/bin/dabbu-cli ./assets/packaging/dabbu-cli.1=/usr/share/man/man1/dabbu-cli.1 ./assets/logo.png=/usr/share/icons/dabbu-cli.png ./assets/packaging/dabbu-cli.desktop=/usr/share/applications/dabbu-cli.desktop
}

# Compile a apk package for linux
function compile_linux_apk {
	echo -e "${colour_blue}Compiling linux_apk${normal}"
	
	fpm -s dir -t apk -p dist/packages/dabbu-cli-`cat version`-linux-alpine-amd64.apk --name dabbu-cli --license gpl3 --version `cat version` --description "A CLI that enables you to access any of your personal information (Gmail, Google Drive, OneDrive, your hard drive, ...) as simple files and folders" --url "https://dabbu-knowledge-platform.github.io" --maintainer "Vedant K (gamemaker1) <dabbuknowledgeplatform@gmail.com>" ./dist/binaries/cli-linux=/usr/bin/dabbu-cli ./assets/packaging/dabbu-cli.1=/usr/share/man/man1/dabbu-cli.1 ./assets/logo.png=/usr/share/icons/dabbu-cli.png ./assets/packaging/dabbu-cli.desktop=/usr/share/applications/dabbu-cli.desktop
}

# Compile a zip for linux
function compile_linux_zip {
	echo -e "${colour_blue}Compiling linux_zip${normal}"
	
	mkdir -p ./dist/generated/linux-zip/

	cp ./readme.md ./dist/generated/linux-zip/
	cp ./license.md ./dist/generated/linux-zip/
	cp ./version ./dist/generated/linux-zip/

	cp ./assets/logo.png ./dist/generated/linux-zip/
	cp ./assets/packaging/dabbu-cli.1 ./dist/generated/linux-zip/
	cp ./assets/packaging/dabbu-cli.desktop ./dist/generated/linux-zip

	cp ./dist/binaries/cli-linux ./dist/generated/linux-zip/dabbu-cli

	cd ./dist/generated/linux-zip/
	zip -9 ../../packages/dabbu-cli-`cat version`-linux-generic-amd64.zip ./*
	cd ../../../
}

# Compile a osxpkg package for linux
function compile_macos_pkg {
	echo -e "${colour_blue}Compiling macos_pkg${normal}"
	
	fpm -s dir -t osxpkg -p dist/packages/dabbu-cli-`cat version`-macos-pkg-amd64.pkg --name dabbu-cli --license gpl3 --version `cat version` --description "A CLI that enables you to access any of your personal information (Gmail, Google Drive, OneDrive, your hard drive, ...) as simple files and folders" --url "https://dabbu-knowledge-platform.github.io" --maintainer "Vedant K (gamemaker1) <dabbuknowledgeplatform@gmail.com>" ./dist/binaries/cli-linux=/usr/bin/dabbu-cli ./assets/packaging/dabbu-cli.1=/usr/share/man/man1/dabbu-cli.1 ./assets/logo.png=/usr/share/icons/dabbu-cli.png ./assets/packaging/dabbu-cli.desktop=/usr/share/applications/dabbu-cli.desktop
}

# Compile a zip for macos
function compile_macos_zip {
	echo -e "${colour_blue}Compiling macos_zip${normal}"

	mkdir -p ./dist/generated/macos-zip/

	cp ./readme.md ./dist/generated/macos-zip/
	cp ./license.md ./dist/generated/macos-zip/
	cp ./version ./dist/generated/macos-zip/

	cp ./assets/logo.png ./dist/generated/macos-zip/
	cp ./assets/packaging/dabbu-cli.1 ./dist/generated/macos-zip/
	cp ./assets/packaging/dabbu-cli.desktop ./dist/generated/macos-zip

	cp ./dist/binaries/cli-macos ./dist/generated/macos-zip/dabbu-cli

	cd ./dist/generated/macos-zip/
	zip -9 ../../packages/dabbu-cli-`cat version`-macos-generic-amd64.zip ./*
	cd ../../../
}

# Compile a zip for win
function compile_win_zip {
	echo -e "${colour_blue}Compiling win_zip${normal}"

	mkdir -p ./dist/generated/win-zip/

	cp ./readme.md ./dist/generated/win-zip/
	cp ./license.md ./dist/generated/win-zip/
	cp ./version ./dist/generated/win-zip/

	cp ./assets/logo.png ./dist/generated/win-zip/
	cp ./assets/packaging/dabbu-cli.1 ./dist/generated/win-zip/dabbu-cli.manualpage
	cp ./assets/packaging/dabbu-cli.desktop ./dist/generated/win-zip/

	cp ./dist/binaries/cli-win.exe ./dist/generated/win-zip/dabbu-cli.exe

	cd ./dist/generated/win-zip/
	zip -9 ../../packages/dabbu-cli-`cat version`-windows-generic-amd64.zip ./*
	cd ../../../
}


# Compile for all machines
function cross_compile {
	# First create the output directory
	mkdir -p ./dist/packages/
	mkdir -p ./dist/generated/
	# Then compile
	compile_linux_deb
	compile_linux_rpm
	compile_linux_pacman
	compile_linux_apk
	compile_linux_zip
	compile_macos_pkg
	compile_macos_zip
	compile_win_zip
}

# Main function
function main {
	# If the first argument is help, show help and exit
	if [ "$1" = "help" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
		help
		exit
	fi

	# Else run the script
	# First build and run pkg to generate binaries
	yarn build
	cp ./package.json ./dist/package.json
	yarn pkg .

	# Then compile the binaries to packages
	cross_compile
}

# Run the script, accepting only one argument
main "$1"
