#!/bin/bash

# run
# Runs the Typescript Compiler on the code and output the compiled code
# to ./dist/compiled/. Then runs the CLI in development mode

# Fail fast
set -e

# First build it
yarn build

# Then run it
env NODE_ENV=development PRINT_ERRORS=true node ./dist/compiled/index.js
