#!/bin/bash

# run
# Runs the Typescript Compiler on the code and output the compiled code
# to ./dist/compiled/. Then runs the CLI in development mode

# Fail fast
set -e

# ANSI colour codes so we can highlight text in the terminal
colour_red="\033[0;31m"
colour_green="\033[0;32m"
colour_blue="\033[0;34m"
colour_cyan="\033[0;36m"

# Escape codes for making text bold and returning it back to normal
bold="\e[1m"
normal="\e[0m"

# First build it
yarn build

echo -e "${bold}${colour_blue}Running CLI...${normal}"
# Then run it
env NODE_ENV=development PRINT_ERRORS=true node ./dist/compiled/index.js
