#!/bin/bash

# dabbu-cli
# Wrapper script that automatically starts the Dabbu Files API Server in the 
# background, then starts the CLI and once the CLI is exited, kills the server 
# as well. The server runs on port 8080, though another port can be specified 
# on the command line as the first parameter.

# Remember which directory the user was in, as we will be changing to the 
# executable's directories before running them. 
# The executables create a _dabbu/ directory while running, to keep that folder 
# in the same directory as the executable, we cd into the executables' 
# directory before running them.
old_pwd="$PWD"

# First start the Files API Server

# cd into that directory
cd "$HOME/.local/opt/dabbu/files-api-server/"

# Switch of logging and pass the arguments on the command line to the server 
# executable. The & at the end starts the command in the background
DO_NOT_LOG_TO_CONSOLE=true ./files-api-server-executable "$*" &
# Get the process ID of the server so we can kill it later
pid=$!

# Run the CLI

# cd into the CLI executable's directory
cd "$HOME/.local/opt/dabbu/cli/"

# Run the CLI in the foreground
./dabbu-cli-executable

# Once the CLI exits, kill the Files API Server by sending it a SIGINT (Ctrl+C) 
# signal
kill -INT $pid

# cd back into the old directory, and give the shell back to the user
cd $old_pwd
