name: CI

# Triggers the workflow on push or pull request events for any branch that has
# this file
on: [push, pull_request]

# This workflow has only one job, since the three jobs are already 
# combined into the `yarn ci` command
jobs:
  ci:
    name: Test and build on node ${{ matrix.node_version }}
    # Run the job on an instance of MacOS (not ubuntu because we need
    # MacOS to build an osxpkg from the binary)
    runs-on: macos-latest
    strategy:
      matrix:
        # Run on node 14
        node_version: ['14.x']
    steps:
      # `git clone` the repo
      - name: Check out repo
        uses: actions/checkout@v1
      # Setup the specified version of node
      - name: Setup node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      # Install dependencies and run the `yarn ci` command
      - name: Test and build
        run: |
          yarn
          yarn ci
      # Save the built binaries
      - name: Uploading built binaries
        uses: actions/upload-artifact@v2
        with:
          name: Dabbu CLI Binaries
          path: |
            dist/binaries/cli-alpine
            dist/binaries/cli-linux
            dist/binaries/cli-macos
            dist/binaries/cli-win.exe
      # Save the built packages
      - name: Uploading packages
        uses: actions/upload-artifact@v2
        with:
          name: Dabbu CLI Packages
          path: dist/packages/
